#!/usr/bin/env bash

# CPU temperature script
cpu_usage=$(~/.config/i3/scripts/sys-stats/cpu_usage)
cpu_temp=$(~/.config/i3/scripts/sys-stats/cpu_temp)

# GPU temperature script
gpu_usage=$(~/.config/i3/scripts/sys-stats/gpu_usage)
gpu_temp=$(~/.config/i3/scripts/sys-stats/gpu_temp)

# Memory usage script
mem_usage=$(~/.config/i3/scripts/sys-stats/memory_usage)


# Show the output in rofi
echo -e "CPU_USAGE\t$cpu_usage\nCPU_TEMP\t$cpu_temp\nGPU_USAGE\t$gpu_usage\nGPU_TEMP\t$gpu_temp\nMEMORY_USAGE\t$mem_usage" | rofi -dmenu -markup-rows -no-fixed-num-lines -lines 5 -columns 2 -width 100 -padding 20 -font "RobotoMono Nerd Font 11" -i

# \CPU_USAGE\t$cpu_usage\nCPU_TEMP\t$cpu_temp\nGPU_USAGE\t$gpu_usage\nGPU_TEMP\t$gpu_temp\nMEMORY_USAGE\t$mem_usage