#!/bin/bash

AccountNum=`cat ~/.accountNum`

API_URL="http://prepaid.desco.org.bd/api/tkdes/customer/getBalance?accountNo=${AccountNum}"

# Make the API request and store the response
response=$(curl -s "$API_URL")

# Extract the "balance" and "currentMonthConsumption" fields using jqdo
balance=$(echo "$response" | jq -r '.data.balance')
# currentMonthConsumption=$(echo "$response" | jq -r '.data.currentMonthConsumption')

# Print the extracted values
# echo "Balance: $balance"
# echo "Current Month Consumption: $currentMonthConsumption"

echo "$balance󰡤"